name: First Rafy Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Print greetings
        run: echo "Hello Rafy"
      - name: Print goodbye
        run: echo "Done - Bello ciao Rafy" 
